// tailwind.config.js
/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#005c55",
        "primary-fixed": "#9cf2e8",
        "primary-fixed-dim": "#80d5cb",
        "primary-container": "#0f766e",
        bfs: "#0f766e",
        "bfs-container": "#d7f3ee",
        "on-bfs": "#083630",
        dfs: "#c2410c",
        "dfs-container": "#ffddcf",
        "on-dfs": "#5a2208",
        match: "#9a6700",
        "match-container": "#fef1c7",
        "on-match": "#4a2c00",
        secondary: "#515f74",
        "secondary-container": "#d5e3fd",
        tertiary: "#952c00",
        "surface": "#fbf9f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3ee",
        "surface-container-high": "#eae8e3",
        "surface-container-highest": "#e4e2dd",
        "surface-variant": "#e4e2dd",
        "outline": "#6e7977",
        "outline-variant": "#bdc9c6",
        "on-surface": "#1b1c19",
        "on-surface-variant": "#3e4947",
        "on-primary": "#ffffff",
        "on-primary-container": "#a3faef",
        "on-primary-fixed-variant": "#00504a",
        "on-secondary-container": "#57657b",
      },
      fontFamily: {
        headline: ["Space Grotesk", "system-ui", "sans-serif"],
        body: ["IBM Plex Sans", "Manrope", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "Fira Code", "monospace"],
      },
    },
  },
  plugins: [],
};
